name: Deploy Lambda

on:
  push:
    branches: [main, master]
    paths:
      - 'server/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: 'us-east-1'
        audience: sts.amazonaws.com

    - name: Package Lambda
      run: |
        zip -r lambda.zip ./*

    - name: Deploy to Lambda
      run: |
        STACK_NAME="lambda-api-stack"  # Replace with your stack name
        FUNCTION_NAME=$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query 'Stacks[0].Outputs[?OutputKey==`FunctionName`].OutputValue' --output text)
        aws lambda update-function-code \
          --function-name ${FUNCTION_NAME} \
          --zip-file fileb://lambda.zip