name: Deploy CloudFormation

on:
  push:
    branches: 
      - main
      - master
    paths:
      - 'cloudformation.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: 'us-east-1'
        audience: 'sts.amazonaws.com'

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation.yml \
          --stack-name lambda-api-stack \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset